"""empty message

Revision ID: 5f3877143e27
Revises: 
Create Date: 2025-09-29 18:52:20.779811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f3877143e27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('imagen', sa.String(length=255), nullable=True),
    sa.Column('imagenDos', sa.String(length=255), nullable=True),
    sa.Column('imagenTres', sa.String(length=255), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('hora_apertura', sa.Time(), nullable=False),
    sa.Column('hora_cierre', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('apellidos', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('mensajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_club', sa.Integer(), nullable=True),
    sa.Column('texto', sa.String(length=500), nullable=False),
    sa.CheckConstraint('((id_usuario IS NOT NULL) AND (id_club IS NULL)) OR ((id_usuario IS NULL) AND (id_club IS NOT NULL))', name='check_existe_1_remitente'),
    sa.ForeignKeyConstraint(['id_club'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_club', sa.Integer(), nullable=False),
    sa.Column('numero_pista', sa.Integer(), nullable=False),
    sa.Column('superficie', sa.Enum('CESPED', 'HORMIGON', 'SINTETICO', name='tiposuperficie'), nullable=False),
    sa.Column('precio_hora', sa.Float(), nullable=False),
    sa.Column('estado_pista', sa.Enum('LIBRE', 'MANTENIMIENTO', name='estadopista'), nullable=False),
    sa.ForeignKeyConstraint(['id_club'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_club', 'numero_pista', name='num_pista_unico')
    )
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_pista', sa.Integer(), nullable=False),
    sa.Column('fecha_reserva', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.CheckConstraint('hora_fin > hora_inicio', name='check_rango_horas_valido'),
    sa.ForeignKeyConstraint(['id_pista'], ['pistas.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservas')
    op.drop_table('pistas')
    op.drop_table('mensajes')
    op.drop_table('usuarios')
    op.drop_table('clubs')
    # ### end Alembic commands ###
