"""empty message

Revision ID: 69eab8bb668e
Revises: e9020e981759
Create Date: 2025-09-29 17:28:00.658649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69eab8bb668e'
down_revision = 'e9020e981759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('imagenDos', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('imagenTres', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('descripcion', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_column('descripcion')
        batch_op.drop_column('imagenTres')
        batch_op.drop_column('imagenDos')
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###
